### ISSUE TITLE
VM resources

### ISSUE THREAD

**Issue by podhrmic** [au-ts/microkit_tutorial#2] opened 2023-10-06 19:03 UTC
Hi @Ivan-Velickovic!
This is a very cool tutorial, I wish there were more tutorials like this:-)
One question about the VMs - could you add resources about how to best build simple Linux images such as the one you provided?
Links to other existing tutorials/examples would be helpful. I know this is not really a part of Microkit, but being able to quickly modify the VM image would be very nice.

**Comment by Ivan-Velickovic** [comment] 2023-10-07 00:31
> Hi @Ivan-Velickovic! This is a very cool tutorial, I wish there were more tutorials like this:-)

Thank you!

> One question about the VMs - could you add resources about how to best build simple Linux images such as the one you provided?

libvmm (https://github.com/au-ts/libvmm) should have everything for doing anything with the VMs. Each example (some exceptions since there's been a lot of development recently) in the project has instructions for reproducing the images, depending on the board. For example the `simple` example is for just booting a simple Linux guest, for QEMU ARM virt the instructions for reproducing the images are here https://github.com/au-ts/libvmm/tree/main/examples/simple/board/qemu_arm_virt.

What exactly do you want to modify about the guest images?

> Links to other existing tutorials/examples would be helpful. I know this is not really a part of Microkit, but being able to quickly modify the VM image would be very nice.

Do you mean the existing seL4 tutorials? We could do that, the eventual goal is to have this tutorial on the seL4 docs website along-side all the other tutorials, but for now it's isolated.

**Comment by podhrmic** [comment] 2023-10-09 15:55
> What exactly do you want to modify about the guest images?

I wanted to add some custom scripts to run after startup. The links you provided are helpful, thank you!

**Comment by Ivan-Velickovic** [comment] 2023-10-10 00:28
Ah okay sure thing. The manual doesn't have a specific guide for adding user-programs to buildroot (yet).

If you look at the `buildroot/` directory of the tutorial repository, you will see the config used as well as the init script that talks to the random word generator. The main configuration option you're looking for is `BR2_ROOTFS_OVERLAY` which is just a path to the overlay directory. Another option is to manually unpack the rootfs, add everything you need and then repack it.

**Comment by Ivan-Velickovic** [comment] 2023-10-10 00:29
I will close this issue since (I think) it is resolved.

**Closed by Ivan-Velickovic** 2023-10-10 00:29 UTC
